// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package wiki.tony.chat.base.pb;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SINGLE_TEXT = 0;</code>
     */
    SINGLE_TEXT(0),
    /**
     * <code>SINGLE_AUDIO = 1;</code>
     */
    SINGLE_AUDIO(1),
    /**
     * <code>GROUP_TEXT = 2;</code>
     */
    GROUP_TEXT(2),
    /**
     * <code>GROUP_AUDIO = 3;</code>
     */
    GROUP_AUDIO(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SINGLE_TEXT = 0;</code>
     */
    public static final int SINGLE_TEXT_VALUE = 0;
    /**
     * <code>SINGLE_AUDIO = 1;</code>
     */
    public static final int SINGLE_AUDIO_VALUE = 1;
    /**
     * <code>GROUP_TEXT = 2;</code>
     */
    public static final int GROUP_TEXT_VALUE = 2;
    /**
     * <code>GROUP_AUDIO = 3;</code>
     */
    public static final int GROUP_AUDIO_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return SINGLE_TEXT;
        case 1: return SINGLE_AUDIO;
        case 2: return GROUP_TEXT;
        case 3: return GROUP_AUDIO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgType)
  }

  public interface MsgDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 to = 1;</code>
     */
    int getTo();

    /**
     * <code>optional uint32 from = 2;</code>
     */
    int getFrom();

    /**
     * <code>optional uint32 ctime = 3;</code>
     */
    int getCtime();

    /**
     * <code>optional .MsgType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    wiki.tony.chat.base.pb.Message.MsgType getType();

    /**
     * <code>optional bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code MsgData}
   */
  public  static final class MsgData extends
      com.google.protobuf.GeneratedMessageLite<
          MsgData, MsgData.Builder> implements
      // @@protoc_insertion_point(message_implements:MsgData)
      MsgDataOrBuilder {
    private MsgData() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int TO_FIELD_NUMBER = 1;
    private int to_;
    /**
     * <code>optional uint32 to = 1;</code>
     */
    public int getTo() {
      return to_;
    }
    /**
     * <code>optional uint32 to = 1;</code>
     */
    private void setTo(int value) {
      
      to_ = value;
    }
    /**
     * <code>optional uint32 to = 1;</code>
     */
    private void clearTo() {
      
      to_ = 0;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private int from_;
    /**
     * <code>optional uint32 from = 2;</code>
     */
    public int getFrom() {
      return from_;
    }
    /**
     * <code>optional uint32 from = 2;</code>
     */
    private void setFrom(int value) {
      
      from_ = value;
    }
    /**
     * <code>optional uint32 from = 2;</code>
     */
    private void clearFrom() {
      
      from_ = 0;
    }

    public static final int CTIME_FIELD_NUMBER = 3;
    private int ctime_;
    /**
     * <code>optional uint32 ctime = 3;</code>
     */
    public int getCtime() {
      return ctime_;
    }
    /**
     * <code>optional uint32 ctime = 3;</code>
     */
    private void setCtime(int value) {
      
      ctime_ = value;
    }
    /**
     * <code>optional uint32 ctime = 3;</code>
     */
    private void clearCtime() {
      
      ctime_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    public wiki.tony.chat.base.pb.Message.MsgType getType() {
      wiki.tony.chat.base.pb.Message.MsgType result = wiki.tony.chat.base.pb.Message.MsgType.forNumber(type_);
      return result == null ? wiki.tony.chat.base.pb.Message.MsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    private void setType(wiki.tony.chat.base.pb.Message.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
    }
    /**
     * <code>optional .MsgType type = 4;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes data = 5;</code>
     */
    private void setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
    }
    /**
     * <code>optional bytes data = 5;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (to_ != 0) {
        output.writeUInt32(1, to_);
      }
      if (from_ != 0) {
        output.writeUInt32(2, from_);
      }
      if (ctime_ != 0) {
        output.writeUInt32(3, ctime_);
      }
      if (type_ != wiki.tony.chat.base.pb.Message.MsgType.SINGLE_TEXT.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, to_);
      }
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, from_);
      }
      if (ctime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, ctime_);
      }
      if (type_ != wiki.tony.chat.base.pb.Message.MsgType.SINGLE_TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Message.MsgData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code MsgData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Message.MsgData, Builder> implements
        // @@protoc_insertion_point(builder_implements:MsgData)
        wiki.tony.chat.base.pb.Message.MsgDataOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Message.MsgData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 to = 1;</code>
       */
      public int getTo() {
        return instance.getTo();
      }
      /**
       * <code>optional uint32 to = 1;</code>
       */
      public Builder setTo(int value) {
        copyOnWrite();
        instance.setTo(value);
        return this;
      }
      /**
       * <code>optional uint32 to = 1;</code>
       */
      public Builder clearTo() {
        copyOnWrite();
        instance.clearTo();
        return this;
      }

      /**
       * <code>optional uint32 from = 2;</code>
       */
      public int getFrom() {
        return instance.getFrom();
      }
      /**
       * <code>optional uint32 from = 2;</code>
       */
      public Builder setFrom(int value) {
        copyOnWrite();
        instance.setFrom(value);
        return this;
      }
      /**
       * <code>optional uint32 from = 2;</code>
       */
      public Builder clearFrom() {
        copyOnWrite();
        instance.clearFrom();
        return this;
      }

      /**
       * <code>optional uint32 ctime = 3;</code>
       */
      public int getCtime() {
        return instance.getCtime();
      }
      /**
       * <code>optional uint32 ctime = 3;</code>
       */
      public Builder setCtime(int value) {
        copyOnWrite();
        instance.setCtime(value);
        return this;
      }
      /**
       * <code>optional uint32 ctime = 3;</code>
       */
      public Builder clearCtime() {
        copyOnWrite();
        instance.clearCtime();
        return this;
      }

      /**
       * <code>optional .MsgType type = 4;</code>
       */
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>optional .MsgType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>optional .MsgType type = 4;</code>
       */
      public wiki.tony.chat.base.pb.Message.MsgType getType() {
        return instance.getType();
      }
      /**
       * <code>optional .MsgType type = 4;</code>
       */
      public Builder setType(wiki.tony.chat.base.pb.Message.MsgType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>optional .MsgType type = 4;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>optional bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>optional bytes data = 5;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgData)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Message.MsgData();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Message.MsgData other = (wiki.tony.chat.base.pb.Message.MsgData) arg1;
          to_ = visitor.visitInt(to_ != 0, to_,
              other.to_ != 0, other.to_);
          from_ = visitor.visitInt(from_ != 0, from_,
              other.from_ != 0, other.from_);
          ctime_ = visitor.visitInt(ctime_ != 0, ctime_,
              other.ctime_ != 0, other.ctime_);
          type_ = visitor.visitInt(type_ != 0, type_,    other.type_ != 0, other.type_);
          data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
              other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  to_ = input.readUInt32();
                  break;
                }
                case 16: {

                  from_ = input.readUInt32();
                  break;
                }
                case 24: {

                  ctime_ = input.readUInt32();
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  type_ = rawValue;
                  break;
                }
                case 42: {

                  data_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Message.MsgData.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MsgData)
    private static final wiki.tony.chat.base.pb.Message.MsgData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Message.MsgData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgData> PARSER;

    public static com.google.protobuf.Parser<MsgData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MsgNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgNotify)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 seq = 1;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code MsgNotify}
   */
  public  static final class MsgNotify extends
      com.google.protobuf.GeneratedMessageLite<
          MsgNotify, MsgNotify.Builder> implements
      // @@protoc_insertion_point(message_implements:MsgNotify)
      MsgNotifyOrBuilder {
    private MsgNotify() {
    }
    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    private void setSeq(int value) {
      
      seq_ = value;
    }
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    private void clearSeq() {
      
      seq_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0) {
        output.writeUInt32(1, seq_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, seq_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Message.MsgNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code MsgNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Message.MsgNotify, Builder> implements
        // @@protoc_insertion_point(builder_implements:MsgNotify)
        wiki.tony.chat.base.pb.Message.MsgNotifyOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Message.MsgNotify.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public int getSeq() {
        return instance.getSeq();
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public Builder setSeq(int value) {
        copyOnWrite();
        instance.setSeq(value);
        return this;
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public Builder clearSeq() {
        copyOnWrite();
        instance.clearSeq();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgNotify)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Message.MsgNotify();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Message.MsgNotify other = (wiki.tony.chat.base.pb.Message.MsgNotify) arg1;
          seq_ = visitor.visitInt(seq_ != 0, seq_,
              other.seq_ != 0, other.seq_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  seq_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Message.MsgNotify.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MsgNotify)
    private static final wiki.tony.chat.base.pb.Message.MsgNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgNotify();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Message.MsgNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgNotify> PARSER;

    public static com.google.protobuf.Parser<MsgNotify> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MsgSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgSync)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 seq = 1;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code MsgSync}
   */
  public  static final class MsgSync extends
      com.google.protobuf.GeneratedMessageLite<
          MsgSync, MsgSync.Builder> implements
      // @@protoc_insertion_point(message_implements:MsgSync)
      MsgSyncOrBuilder {
    private MsgSync() {
    }
    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    private void setSeq(int value) {
      
      seq_ = value;
    }
    /**
     * <code>optional uint32 seq = 1;</code>
     */
    private void clearSeq() {
      
      seq_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0) {
        output.writeUInt32(1, seq_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, seq_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Message.MsgSync prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code MsgSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Message.MsgSync, Builder> implements
        // @@protoc_insertion_point(builder_implements:MsgSync)
        wiki.tony.chat.base.pb.Message.MsgSyncOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Message.MsgSync.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public int getSeq() {
        return instance.getSeq();
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public Builder setSeq(int value) {
        copyOnWrite();
        instance.setSeq(value);
        return this;
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       */
      public Builder clearSeq() {
        copyOnWrite();
        instance.clearSeq();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgSync)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Message.MsgSync();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Message.MsgSync other = (wiki.tony.chat.base.pb.Message.MsgSync) arg1;
          seq_ = visitor.visitInt(seq_ != 0, seq_,
              other.seq_ != 0, other.seq_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  seq_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Message.MsgSync.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MsgSync)
    private static final wiki.tony.chat.base.pb.Message.MsgSync DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgSync();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Message.MsgSync getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgSync> PARSER;

    public static com.google.protobuf.Parser<MsgSync> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MsgSyncDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgSyncData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    java.util.List<wiki.tony.chat.base.pb.Message.MsgData> 
        getMessagesList();
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    wiki.tony.chat.base.pb.Message.MsgData getMessages(int index);
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    int getMessagesCount();
  }
  /**
   * Protobuf type {@code MsgSyncData}
   */
  public  static final class MsgSyncData extends
      com.google.protobuf.GeneratedMessageLite<
          MsgSyncData, MsgSyncData.Builder> implements
      // @@protoc_insertion_point(message_implements:MsgSyncData)
      MsgSyncDataOrBuilder {
    private MsgSyncData() {
      messages_ = emptyProtobufList();
    }
    public static final int MESSAGES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<wiki.tony.chat.base.pb.Message.MsgData> messages_;
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    public java.util.List<wiki.tony.chat.base.pb.Message.MsgData> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    public java.util.List<? extends wiki.tony.chat.base.pb.Message.MsgDataOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    public wiki.tony.chat.base.pb.Message.MsgData getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    public wiki.tony.chat.base.pb.Message.MsgDataOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }
    private void ensureMessagesIsMutable() {
      if (!messages_.isModifiable()) {
        messages_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(messages_);
       }
    }

    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void setMessages(
        int index, wiki.tony.chat.base.pb.Message.MsgData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMessagesIsMutable();
      messages_.set(index, value);
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void setMessages(
        int index, wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
      ensureMessagesIsMutable();
      messages_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void addMessages(wiki.tony.chat.base.pb.Message.MsgData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMessagesIsMutable();
      messages_.add(value);
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void addMessages(
        int index, wiki.tony.chat.base.pb.Message.MsgData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMessagesIsMutable();
      messages_.add(index, value);
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void addMessages(
        wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
      ensureMessagesIsMutable();
      messages_.add(builderForValue.build());
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void addMessages(
        int index, wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
      ensureMessagesIsMutable();
      messages_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void addAllMessages(
        java.lang.Iterable<? extends wiki.tony.chat.base.pb.Message.MsgData> values) {
      ensureMessagesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, messages_);
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void clearMessages() {
      messages_ = emptyProtobufList();
    }
    /**
     * <code>repeated .MsgData messages = 1;</code>
     */
    private void removeMessages(int index) {
      ensureMessagesIsMutable();
      messages_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Message.MsgSyncData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Message.MsgSyncData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code MsgSyncData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Message.MsgSyncData, Builder> implements
        // @@protoc_insertion_point(builder_implements:MsgSyncData)
        wiki.tony.chat.base.pb.Message.MsgSyncDataOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Message.MsgSyncData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public java.util.List<wiki.tony.chat.base.pb.Message.MsgData> getMessagesList() {
        return java.util.Collections.unmodifiableList(
            instance.getMessagesList());
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public int getMessagesCount() {
        return instance.getMessagesCount();
      }/**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public wiki.tony.chat.base.pb.Message.MsgData getMessages(int index) {
        return instance.getMessages(index);
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder setMessages(
          int index, wiki.tony.chat.base.pb.Message.MsgData value) {
        copyOnWrite();
        instance.setMessages(index, value);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder setMessages(
          int index, wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
        copyOnWrite();
        instance.setMessages(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder addMessages(wiki.tony.chat.base.pb.Message.MsgData value) {
        copyOnWrite();
        instance.addMessages(value);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder addMessages(
          int index, wiki.tony.chat.base.pb.Message.MsgData value) {
        copyOnWrite();
        instance.addMessages(index, value);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder addMessages(
          wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
        copyOnWrite();
        instance.addMessages(builderForValue);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder addMessages(
          int index, wiki.tony.chat.base.pb.Message.MsgData.Builder builderForValue) {
        copyOnWrite();
        instance.addMessages(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends wiki.tony.chat.base.pb.Message.MsgData> values) {
        copyOnWrite();
        instance.addAllMessages(values);
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder clearMessages() {
        copyOnWrite();
        instance.clearMessages();
        return this;
      }
      /**
       * <code>repeated .MsgData messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        copyOnWrite();
        instance.removeMessages(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgSyncData)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Message.MsgSyncData();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          messages_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Message.MsgSyncData other = (wiki.tony.chat.base.pb.Message.MsgSyncData) arg1;
          messages_= visitor.visitList(messages_, other.messages_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!messages_.isModifiable()) {
                    messages_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(messages_);
                  }
                  messages_.add(
                      input.readMessage(wiki.tony.chat.base.pb.Message.MsgData.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Message.MsgSyncData.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MsgSyncData)
    private static final wiki.tony.chat.base.pb.Message.MsgSyncData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgSyncData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Message.MsgSyncData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgSyncData> PARSER;

    public static com.google.protobuf.Parser<MsgSyncData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
