// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package wiki.tony.chat.base.pb;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AuthReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code AuthReq}
   */
  public  static final class AuthReq extends
      com.google.protobuf.GeneratedMessageLite<
          AuthReq, AuthReq.Builder> implements
      // @@protoc_insertion_point(message_implements:AuthReq)
      AuthReqOrBuilder {
    private AuthReq() {
      token_ = "";
    }
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    private void setUid(int value) {
      
      uid_ = value;
    }
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    private void clearUid() {
      
      uid_ = 0;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.String token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      return token_;
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(token_);
    }
    /**
     * <code>optional string token = 2;</code>
     */
    private void setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
    }
    /**
     * <code>optional string token = 2;</code>
     */
    private void clearToken() {
      
      token_ = getDefaultInstance().getToken();
    }
    /**
     * <code>optional string token = 2;</code>
     */
    private void setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeUInt32(1, uid_);
      }
      if (!token_.isEmpty()) {
        output.writeString(2, getToken());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uid_);
      }
      if (!token_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getToken());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Auth.AuthReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code AuthReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Auth.AuthReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthReq)
        wiki.tony.chat.base.pb.Auth.AuthReqOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Auth.AuthReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public int getUid() {
        return instance.getUid();
      }
      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        copyOnWrite();
        instance.setUid(value);
        return this;
      }
      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public Builder clearUid() {
        copyOnWrite();
        instance.clearUid();
        return this;
      }

      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        return instance.getToken();
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        return instance.getTokenBytes();
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setToken(value);
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        copyOnWrite();
        instance.clearToken();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AuthReq)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Auth.AuthReq();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Auth.AuthReq other = (wiki.tony.chat.base.pb.Auth.AuthReq) arg1;
          uid_ = visitor.visitInt(uid_ != 0, uid_,
              other.uid_ != 0, other.uid_);
          token_ = visitor.visitString(!token_.isEmpty(), token_,
              !other.token_.isEmpty(), other.token_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  uid_ = input.readUInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  token_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Auth.AuthReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AuthReq)
    private static final wiki.tony.chat.base.pb.Auth.AuthReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AuthReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Auth.AuthReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthReq> PARSER;

    public static com.google.protobuf.Parser<AuthReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthResp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional uint32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code AuthResp}
   */
  public  static final class AuthResp extends
      com.google.protobuf.GeneratedMessageLite<
          AuthResp, AuthResp.Builder> implements
      // @@protoc_insertion_point(message_implements:AuthResp)
      AuthRespOrBuilder {
    private AuthResp() {
      message_ = "";
    }
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    private void setUid(int value) {
      
      uid_ = value;
    }
    /**
     * <code>optional uint32 uid = 1;</code>
     */
    private void clearUid() {
      
      uid_ = 0;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>optional uint32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>optional uint32 code = 2;</code>
     */
    private void setCode(int value) {
      
      code_ = value;
    }
    /**
     * <code>optional uint32 code = 2;</code>
     */
    private void clearCode() {
      
      code_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.String message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    private void setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
    }
    /**
     * <code>optional string message = 3;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>optional string message = 3;</code>
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeUInt32(1, uid_);
      }
      if (code_ != 0) {
        output.writeUInt32(2, code_);
      }
      if (!message_.isEmpty()) {
        output.writeString(3, getMessage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uid_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, code_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMessage());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wiki.tony.chat.base.pb.Auth.AuthResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wiki.tony.chat.base.pb.Auth.AuthResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code AuthResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wiki.tony.chat.base.pb.Auth.AuthResp, Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthResp)
        wiki.tony.chat.base.pb.Auth.AuthRespOrBuilder {
      // Construct using wiki.tony.chat.base.pb.Auth.AuthResp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public int getUid() {
        return instance.getUid();
      }
      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        copyOnWrite();
        instance.setUid(value);
        return this;
      }
      /**
       * <code>optional uint32 uid = 1;</code>
       */
      public Builder clearUid() {
        copyOnWrite();
        instance.clearUid();
        return this;
      }

      /**
       * <code>optional uint32 code = 2;</code>
       */
      public int getCode() {
        return instance.getCode();
      }
      /**
       * <code>optional uint32 code = 2;</code>
       */
      public Builder setCode(int value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>optional uint32 code = 2;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AuthResp)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wiki.tony.chat.base.pb.Auth.AuthResp();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          wiki.tony.chat.base.pb.Auth.AuthResp other = (wiki.tony.chat.base.pb.Auth.AuthResp) arg1;
          uid_ = visitor.visitInt(uid_ != 0, uid_,
              other.uid_ != 0, other.uid_);
          code_ = visitor.visitInt(code_ != 0, code_,
              other.code_ != 0, other.code_);
          message_ = visitor.visitString(!message_.isEmpty(), message_,
              !other.message_.isEmpty(), other.message_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  uid_ = input.readUInt32();
                  break;
                }
                case 16: {

                  code_ = input.readUInt32();
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  message_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (wiki.tony.chat.base.pb.Auth.AuthResp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AuthResp)
    private static final wiki.tony.chat.base.pb.Auth.AuthResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AuthResp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static wiki.tony.chat.base.pb.Auth.AuthResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthResp> PARSER;

    public static com.google.protobuf.Parser<AuthResp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
